//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTResultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class result11
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public string examterm { get; set; }
        public Nullable<double> eng1131 { get; set; }
        public Nullable<double> phy1132 { get; set; }
        public Nullable<double> bus1123 { get; set; }
        public Nullable<double> mat1134 { get; set; }
        public Nullable<double> eee1135 { get; set; }
        public Nullable<double> eee11p6 { get; set; }
        public Nullable<double> cse1127 { get; set; }
        public Nullable<double> cse11p8 { get; set; }

    }
}
