//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTResultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class result42
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public string examterm { get; set; }
        public Nullable<double> cse4231 { get; set; }
        public Nullable<double> cse4232 { get; set; }
        public Nullable<double> cse42p3 { get; set; }
        public Nullable<double> cse4234 { get; set; }
        public Nullable<double> cse42p5 { get; set; }
        public Nullable<double> cse4246 { get; set; }
        public Nullable<double> cse4227 { get; set; }
    
        public virtual student student { get; set; }
    }
}
