//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTResultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class result32
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public string examterm { get; set; }
        public Nullable<double> cse3221 { get; set; }
        public Nullable<double> cse3232 { get; set; }
        public Nullable<double> cse3233 { get; set; }
        public Nullable<double> cse32p4 { get; set; }
        public Nullable<double> cse3235 { get; set; }
        public Nullable<double> cse32p6 { get; set; }
        public Nullable<double> cse3237 { get; set; }
        public Nullable<double> cse32p8 { get; set; }
        public Nullable<double> cse32p9 { get; set; }
    }
}
