//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTResultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class result21
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public string examterm { get; set; }
        public Nullable<double> mat2131 { get; set; }
        public Nullable<double> che2122 { get; set; }
        public Nullable<double> cse2133 { get; set; }
        public Nullable<double> cse2134 { get; set; }
        public Nullable<double> cse2135 { get; set; }
        public Nullable<double> cse21p6 { get; set; }
        public Nullable<double> cse2137 { get; set; }
        public Nullable<double> cse21p8 { get; set; }
    }
}
