//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTResultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class result31
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public string examterm { get; set; }
        public Nullable<double> mat3131 { get; set; }
        public Nullable<double> cse3122 { get; set; }
        public Nullable<double> cse3133 { get; set; }
        public Nullable<double> cse3134 { get; set; }
        public Nullable<double> cse31p5 { get; set; }
        public Nullable<double> cse3136 { get; set; }
        public Nullable<double> cse31p7 { get; set; }
        public Nullable<double> cse31p8 { get; set; }
        public Nullable<double> cse31p9 { get; set; }
    
        public virtual student student { get; set; }
    }
}
