//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTResultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class result22
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public string examterm { get; set; }
        public Nullable<double> eco2221 { get; set; }
        public Nullable<double> cse2232 { get; set; }
        public Nullable<double> cse22p3 { get; set; }
        public Nullable<double> cse2234 { get; set; }
        public Nullable<double> cse22p5 { get; set; }
        public Nullable<double> cse2236 { get; set; }
        public Nullable<double> cse22p7 { get; set; }
        public Nullable<double> cse2238 { get; set; }
        public Nullable<double> cse22p9 { get; set; }
    }
}
