//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTResultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class result41
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public string examterm { get; set; }
        public Nullable<double> cse4121 { get; set; }
        public Nullable<double> cse4132 { get; set; }
        public Nullable<double> cse4133 { get; set; }
        public Nullable<double> cse41p4 { get; set; }
        public Nullable<double> cse4135 { get; set; }
        public Nullable<double> cse41p6 { get; set; }
        public Nullable<double> cse4137 { get; set; }
        public Nullable<double> cse41p8 { get; set; }
    
        public virtual student student { get; set; }
    }
}
