//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTResultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public string fullname { get; set; }
        public string studycenter { get; set; }
        public string batchno { get; set; }
        public string academicsession { get; set; }
        public string fathername { get; set; }
        public string mothername { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string mobileno { get; set; }
        public string bloodgroup { get; set; }
        public string address { get; set; }

    }
}
