//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTResultSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.result11 = new HashSet<result11>();
            this.result12 = new HashSet<result12>();
            this.result21 = new HashSet<result21>();
            this.result22 = new HashSet<result22>();
            this.result31 = new HashSet<result31>();
            this.result32 = new HashSet<result32>();
            this.result41 = new HashSet<result41>();
            this.result42 = new HashSet<result42>();
        }

        public int id { get; set; }

        [Display(Name = "Student ID: ")]
        [RegularExpression("[0-9]{2}-[0-9]{1}-[0-9]{2}-[0-9]{3}-[0-9]{3}", ErrorMessage="Please enter Student ID Correctly!")]
        public string studentid { get; set; }

        [Display(Name = "Full Name: ")]
        public string fullname { get; set; }

        [Display(Name = "Study Center: ")]
        public string studycenter { get; set; }

        [Display(Name = "Student Batch No: ")]
        public string batchno { get; set; }

        [Display(Name = "Acdemic Session: ")]
        public string academicsession { get; set; }

        [Display(Name = "Father Name: ")]
        public string fathername { get; set; }

        [Display(Name = "Mother Name: ")]
        public string mothername { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date of birth: ")]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        public DateTime? dob { get; set; }
        //public Nullable<System.DateTime> dob { get; set; }

        [Display(Name = "Mobile No: ")]
        public string mobileno { get; set; }

        [Display(Name = "Blood Group: ")]
        public string bloodgroup { get; set; }

        [Display(Name = "Address: ")]
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result11> result11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result12> result12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result21> result21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result22> result22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result31> result31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result32> result32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result41> result41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result42> result42 { get; set; }
    }
}